# Generated by Django 3.2.6 on 2021-08-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('UniversityName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniversityID', models.FloatField()),
                ('doctorsname', models.CharField(max_length=40)),
            ],
        ),
    ]
